{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "sentry-kubernetes.labels" . | indent 4 }}
  name: {{ template "sentry-kubernetes.fullname" . }}
rules:
  # Custom rules inclusion
  {{ if .Values.rbac.custom_rules }}
    {{- toYaml .Values.rbac.custom_rules | nindent 4 }}
  {{ else }}
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  {{ end }}
{{- end -}}