name: Auto Label Conflicts
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v3
        with:
          conflict_label_name: "conflicts"
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          detect_merge_changes: false # or true to handle as conflicts
          conflict_comment: |
            :wave: Hi, @${author},
            I detected conflicts against the base branch :speak_no_evil:
            You'll want to sync :arrows_counterclockwise: your branch with upstream!
